#!/bin/sh

PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
PKG=/usr/local/sbin/pkg
POUDRIERE=/usr/local/bin/poudriere
CONF=~/.build-packages.conf

err() {
  echo "!!! $*"
}

msg() {
    echo " >>> $*"
}

html_css() {
cat << EOF
    <link rel="stylesheet" type="text/css" href="pkg.css">
EOF
}

html_prolog() {
    echo "<h1>FreeBSD ${HTMLVERSION} unofficial repository for ${ARCH}</h1>"
    echo "<p>"
    echo "This is an <b>unofficial</b> FreeBSD ${HTMLVERSION} repository for ${ARCH}."
    echo "</p>"
    echo "Current packages with their options:"
}

html_header() {
cat << EOF
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
EOF

    echo "  <title>FreeBSD repository for ${ARCH}</title>"
    html_css
    echo '</head>'
}

html_table() {
    echo ""
    echo "<table>"
    for package in `ls ${PACKAGEDIR}/*.txz | sort -f`; do
        echo "<tr><td>"
        ${PKG} query -F ${package} "  <a href=http://pkg.uzsolt.hu/${ARCHL}/All/%n-%v.txz>%n-%v</a><br>
  (<a class=freshports href=http://freshports.org/%o>%o</a>)</td>
<td>"
        if [ `${PKG} query -F ${package} "%#O"` -gt 0 ]; then
            #echo "  <ul style='list-style-type:none'>"
            echo "  <ul>"
            ${PKG} query -F ${package} "  <li class='option %Ov'>%Ok - %Ov</li>"
            echo "  </ul>"
        fi
        echo "</td></tr>"
        echo ""
    done
}

html_tail() {
    echo "</table>"
    echo "<p><b>Total `ls ${PACKAGEDIR}/*.txz | wc -l` packages.</b></p>"
    echo "<p>"
    echo "This repository is maintained by Zsolt Udvari (udvzsolt gmail com). Generated at " `date +"%Y.%m.%d. %H:%M:%S"`
    echo "</p>"
    echo "</html>"
}

generate_html_table() {
    html_header
    html_prolog
    html_table
    html_tail
}

check_updates() {
    OUTDATED_PACKAGES=""
    for f in ${PACKAGEDIR}/*.txz; do
        ORIGIN=`${PKG} query -F ${f} '%o'`
        VER1=`${PKG} query -F ${f} '%v'`
        VER2=`make -C /usr/home/poudriere/ports/default/${ORIGIN} -V PKGVERSION`
        if [ `${PKG} version -t ${VER1} ${VER2}` = '<' ]; then
            OUTDATED_PACKAGES="${OUTDATED_PACKAGES} ${ORIGIN}"
        fi
    done
    echo ${OUTDATED_PACKAGES}
}

build_information() {
    msg LISTFILE=${LISTFILE}
    msg JAIL=${JAIL}
    msg PORTS=${PORTS}
    if [ -n "${PSET}" ]; then
        msg PSET=${PSET}
    fi
    if [ -n "${HTMLFILE}" ]; then
        msg "HTMLFILE=${HTMLFILE}"
    else
        msg "No HTML output."
    fi
}

read_config() {
  if [ -r "${CONF}" ]; then
    . ${CONF}
  else
    err "Does not exist ${CONF} file. Exit."
    return 1
  fi
}

parse_params() {
  if [ $# -lt 1 ]; then
    err "Missing jail. Exit."
    return 1
  else
    B_ARCH=$1
    B_CMD=$2
    [ -z "${B_CMD}" ] && B_CMD=build
  fi
}

load_jail_params() {
  if type "jail_${B_ARCH}" > /dev/null 2>&1 ; then
    jail_${B_ARCH}
    [ -z "${LISTFILE}" ] && { err "LISTFILE isn't set"; return 1; }
    [ -z "${JAIL}" ] && { err "JAIL isn't set"; return 1; }
    [ -z "${PORTS}" ] && { err "PORTS isn't set"; return 1; }
    return 0
  else
    err "Jail ${B_ARCH} does not exist (jail_${B_ARCH}). Exit."
    return 1
  fi
}

read_config || exit 1
parse_params $@ || exit 1
load_jail_params || exit 1

case "${B_CMD}" in
    build)
        POSTFIX=""
        [ -n "${PSET}" ] && POSTFIX="-z ${PSET}"
        build_information
        /usr/bin/nice -n 15 ${POUDRIERE} bulk -j ${JAIL} -p ${PORTS} -f ${LISTFILE} ${POSTFIX}
        [ -n "${HTMLFILE}" ] && generate_html_table > ${HTMLFILE}
        ;;
    check)
        check_updates
        ;;
    html)
        generate_html_table > ${HTMLFILE}
        ;;
    *)
        echo Unknown command: $1.
        exit 1
esac

